# Generated by Django 3.0.3 on 2020-02-26 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoleDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=255, null=True, unique=True)),
                ('password', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('mobile', models.BigIntegerField(blank=True, default='', null=True)),
                ('address', models.TextField(blank=True, default='', max_length=255, null=True)),
                ('gender', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('verify_link', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('otp', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('otp_time', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('is_active', models.NullBooleanField(default=0)),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_panel_app.UserRole')),
            ],
        ),
    ]
